/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingCoursesRouteImport } from './routes/_marketing/courses'
import { Route as MarketingContributorsRouteImport } from './routes/_marketing/contributors'
import { Route as MarketingContributeRouteImport } from './routes/_marketing/contribute'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as CourseIdIndexRouteImport } from './routes/course/$id/index'
import { Route as CourseIdDashboardRouteImport } from './routes/course/$id/dashboard'
import { Route as CourseIdUnitIdIndexRouteImport } from './routes/course/$id/$unitId/index'
import { Route as CourseIdUnitIdLessonIdIndexRouteImport } from './routes/course/$id/$unitId/$lessonId/index'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCoursesRoute = MarketingCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContributorsRoute = MarketingContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContributeRoute = MarketingContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const CourseIdIndexRoute = CourseIdIndexRouteImport.update({
  id: '/course/$id/',
  path: '/course/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIdDashboardRoute = CourseIdDashboardRouteImport.update({
  id: '/course/$id/dashboard',
  path: '/course/$id/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIdUnitIdIndexRoute = CourseIdUnitIdIndexRouteImport.update({
  id: '/course/$id/$unitId/',
  path: '/course/$id/$unitId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIdUnitIdLessonIdIndexRoute =
  CourseIdUnitIdLessonIdIndexRouteImport.update({
    id: '/course/$id/$unitId/$lessonId/',
    path: '/course/$id/$unitId/$lessonId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/contribute': typeof MarketingContributeRoute
  '/contributors': typeof MarketingContributorsRoute
  '/courses': typeof MarketingCoursesRoute
  '/': typeof MarketingIndexRoute
  '/course/$id/dashboard': typeof CourseIdDashboardRoute
  '/course/$id': typeof CourseIdIndexRoute
  '/course/$id/$unitId': typeof CourseIdUnitIdIndexRoute
  '/course/$id/$unitId/$lessonId': typeof CourseIdUnitIdLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/contribute': typeof MarketingContributeRoute
  '/contributors': typeof MarketingContributorsRoute
  '/courses': typeof MarketingCoursesRoute
  '/': typeof MarketingIndexRoute
  '/course/$id/dashboard': typeof CourseIdDashboardRoute
  '/course/$id': typeof CourseIdIndexRoute
  '/course/$id/$unitId': typeof CourseIdUnitIdIndexRoute
  '/course/$id/$unitId/$lessonId': typeof CourseIdUnitIdLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/contribute': typeof MarketingContributeRoute
  '/_marketing/contributors': typeof MarketingContributorsRoute
  '/_marketing/courses': typeof MarketingCoursesRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/course/$id/dashboard': typeof CourseIdDashboardRoute
  '/course/$id/': typeof CourseIdIndexRoute
  '/course/$id/$unitId/': typeof CourseIdUnitIdIndexRoute
  '/course/$id/$unitId/$lessonId/': typeof CourseIdUnitIdLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/todos'
    | '/about'
    | '/contact'
    | '/contribute'
    | '/contributors'
    | '/courses'
    | '/'
    | '/course/$id/dashboard'
    | '/course/$id'
    | '/course/$id/$unitId'
    | '/course/$id/$unitId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/todos'
    | '/about'
    | '/contact'
    | '/contribute'
    | '/contributors'
    | '/courses'
    | '/'
    | '/course/$id/dashboard'
    | '/course/$id'
    | '/course/$id/$unitId'
    | '/course/$id/$unitId/$lessonId'
  id:
    | '__root__'
    | '/_marketing'
    | '/dashboard'
    | '/todos'
    | '/_marketing/about'
    | '/_marketing/contact'
    | '/_marketing/contribute'
    | '/_marketing/contributors'
    | '/_marketing/courses'
    | '/_marketing/'
    | '/course/$id/dashboard'
    | '/course/$id/'
    | '/course/$id/$unitId/'
    | '/course/$id/$unitId/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  TodosRoute: typeof TodosRoute
  CourseIdDashboardRoute: typeof CourseIdDashboardRoute
  CourseIdIndexRoute: typeof CourseIdIndexRoute
  CourseIdUnitIdIndexRoute: typeof CourseIdUnitIdIndexRoute
  CourseIdUnitIdLessonIdIndexRoute: typeof CourseIdUnitIdLessonIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/courses': {
      id: '/_marketing/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof MarketingCoursesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contributors': {
      id: '/_marketing/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof MarketingContributorsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contribute': {
      id: '/_marketing/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof MarketingContributeRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/course/$id/': {
      id: '/course/$id/'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof CourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$id/dashboard': {
      id: '/course/$id/dashboard'
      path: '/course/$id/dashboard'
      fullPath: '/course/$id/dashboard'
      preLoaderRoute: typeof CourseIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$id/$unitId/': {
      id: '/course/$id/$unitId/'
      path: '/course/$id/$unitId'
      fullPath: '/course/$id/$unitId'
      preLoaderRoute: typeof CourseIdUnitIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$id/$unitId/$lessonId/': {
      id: '/course/$id/$unitId/$lessonId/'
      path: '/course/$id/$unitId/$lessonId'
      fullPath: '/course/$id/$unitId/$lessonId'
      preLoaderRoute: typeof CourseIdUnitIdLessonIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingContributeRoute: typeof MarketingContributeRoute
  MarketingContributorsRoute: typeof MarketingContributorsRoute
  MarketingCoursesRoute: typeof MarketingCoursesRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingContributeRoute: MarketingContributeRoute,
  MarketingContributorsRoute: MarketingContributorsRoute,
  MarketingCoursesRoute: MarketingCoursesRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  DashboardRoute: DashboardRoute,
  TodosRoute: TodosRoute,
  CourseIdDashboardRoute: CourseIdDashboardRoute,
  CourseIdIndexRoute: CourseIdIndexRoute,
  CourseIdUnitIdIndexRoute: CourseIdUnitIdIndexRoute,
  CourseIdUnitIdLessonIdIndexRoute: CourseIdUnitIdLessonIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
